### ISSUE TITLE
Partial mode?

### ISSUE THREAD

**Issue by glenjamin** [andyt530/az2tf#1]
Hello!

I've just been pointed at this repo, it looks ace - good to see someone is going through handling all these cases.

I did a proof-of-concept myself a while back, but never spent much time handling all the resources we have in use: https://github.com/glenjamin/azure-terraform-generate

One thing that might help with the speed / completeness issues would be if there was a way to scope this down to do individual resources or groups at once, to provide a bit more fine-grained control.

In our case we have a few hundred VMs and associated resources, and we'd be looking to import into terraform gradually.

Hope that makes sense, cheers!

**Comment by peterb154** [comment]
@glenjamin, I just completed a good sized project with az2tf, it worked great. @andyt530 has built a great tool here. For our project, we imported one resource group at a time to manage the scope. Incidentally, each resource group will be maintained as a separate state & github repo (and workspace in Terraform Enterprise).  

Just run  ./az2tf.sh $SUBSCRIPTION $RESOURCE_GROUP and it will output a ./tf.$SUBSCRIPTION_$RESOURCE_GROUP directory with resources only from that rg. Works like a charm.

**Comment by andyt530** [comment]
az2tf now allows scoping down to an individual resource group. Also via the -r switch your can pick out specific resource types.  I didn't adopt the idea of having separate directories per resource group because this would preclude you performing several runs and getting an incremental build up resource group by resource group.
